services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-v2}
    env_file:
      - .env
    volumes:
      # Zone de stockage des photos/vidéos sur ton disque de 1 To
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always
    ports:
      # Optionnel : accès direct sans Traefik (debug/local)
      - "2283:2283"
    networks:
      - backend
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`${IMMICH_FQDN}`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=mytlschallenge
      - traefik.http.services.immich.loadbalancer.server.port=2283

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-v2}
    env_file:
      - .env
    volumes:
      - immich_model-cache:/cache
    restart: always
    networks:
      - backend

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always
    networks:
      - backend

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # Décommente si le disque /srv est un HDD classique (non SSD)
      DB_STORAGE_TYPE: "HDD"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
  traefik_proxy:
    external: true
    # même réseau Traefik que pour Nextcloud/n8n
    name: n8n-traefik_default

volumes:
  immich_model-cache:
